### ISSUE TITLE
Undefined type 'Dotenv\Dotenv'.intelephense

### ISSUE THREAD

**Issue by MahaLakshmiMurugan** [yii-starter-kit/yii2-starter-kit#778]
![yii2-dontenv](https://user-images.githubusercontent.com/32451788/119340131-b6f8f600-bcaf-11eb-832f-925e0419012e.png)

git clone git@github.com:yii-starter-kit/yii2-starter-kit.git - done
composer install - done
v host setup - done
while running the migration  I'm getting this error

**Comment by XzAeRo** [comment]
Resolved in the latest release!
