### ISSUE TITLE
How to compiler Yii2 starter kit project by JIT.

### ISSUE THREAD

**Issue by h3d-tuannq** [yii-starter-kit/yii2-starter-kit#785]
Hi Admin, I using Yii starter kit for my project.
I run project on php 8, how to i can compiler my project to assembly code by JIT and run it.
thanks for answer.

**Comment by XzAeRo** [comment]
JIT is the way the compiler works. It compiles them when they are invoked. It can't be compiled to "assembly code", like you would compile Golang, Java, C/C++, which is at build time.

Since we support PHP8 you can use more aggressive JIT options.
Learn more here: https://php.watch/versions/8.0/JIT
